name: Backend CI/CD

on:
    push:
        paths: ["backend/**"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Checkout repo
              uses: actions/checkout@v3

            - name: 🏗 Enable Bun
              uses: oven-sh/setup-bun@v1

            - name: 📦 Install dependencies
              run: bun i

            - name: 🏗 Apply all pending migrations to the database
              run: cd backend && bun prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  MIGRATE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
