name: Backend CI/CD

on:
    push:
        paths: ["backend/**"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Checkout repo
              uses: actions/checkout@v3

            - name: 🏗 Enable PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: "latest"

            - name: 🏗 Setup Node.js environment
              uses: actions/setup-node@main
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: 📦 Install dependencies
              run: pnpm i --no-frozen-lockfile

            - name: 🏗 Apply all pending migrations to the database
              run: cd backend && pnpm prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  MIGRATE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
