name: Continuous Deploy

on:
    push:
        branches:
            - "main"
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 🏗 Checkout repo
              uses: actions/checkout@v3

            - name: 🏗 Enable PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: "latest"

            - name: 🏗 Setup Node.js environment
              uses: actions/setup-node@main
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: 🏗 Cache Next.js files
              uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.next/cache
                  # Generate a new cache whenever packages or source files change.
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  # If source files changed but packages didn't, rebuild from a prior cache.
                  restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

            - name: 📦 Install dependencies
              run: pnpm i

            - name: 🚀 Build the app
              run: pnpm build

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Deploy to AWS S3
              run: aws s3 sync ./out s3://maple-sim --delete

            - name: Invalidate existing pages
              run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
